name: Deploy to Google Cloud Storage

on:
  push:
    branches:
      - main  # Adjust this if you're using a different branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Google Cloud Authentication
      env:
        GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
      run: |
        echo "$GCP_SA_KEY" > service-account.json
        gcloud auth activate-service-account --key-file=service-account.json

    - name: Upload to Google Cloud Storage
      run: |
        gsutil cp -r ./ gs://business-news-blog/
