name: Deploy to Google Cloud Storage

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Deploy to GCS
      uses: google-github-actions/upload-cloud-storage@v0.5.0
      with:
        path: ./  # This will select all files in the root of the repository
        destination: gs://business-news-blog/  # This will place files at the root of the bucket
      env:
        GCS_SA_KEY: ${{ secrets.GCS_SA_KEY }}
